-- =========================================================
-- Finance SQL Training Dataset Generator (PostgreSQL)
-- Reproducible, realistic, and "classroom sized"
-- Uses deterministic pseudo-random values based on md5()
-- =========================================================

-- ---------- Clean start ----------
DROP VIEW IF EXISTS v_finance_activity;

DROP TABLE IF EXISTS payment_applications;
DROP TABLE IF EXISTS payments;

DROP TABLE IF EXISTS journal_lines;
DROP TABLE IF EXISTS journal_entries;

DROP TABLE IF EXISTS bill_lines;
DROP TABLE IF EXISTS bills;

DROP TABLE IF EXISTS invoice_lines;
DROP TABLE IF EXISTS invoices;

DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS vendors;
DROP TABLE IF EXISTS departments;
DROP TABLE IF EXISTS chart_of_accounts;

DROP FUNCTION IF EXISTS det_int(text, int);
DROP FUNCTION IF EXISTS det_num(text, numeric, numeric);

-- ---------- Deterministic helpers ----------
-- Returns deterministic integer in [0, mod-1]
CREATE FUNCTION det_int(seed text, mod int)
RETURNS int
LANGUAGE SQL
IMMUTABLE
AS $$
  SELECT ( (('x' || substr(md5(seed), 1, 8))::bit(32)::int) % mod + mod ) % mod;
$$;

-- Returns deterministic numeric in [min_val, max_val]
CREATE FUNCTION det_num(seed text, min_val numeric, max_val numeric)
RETURNS numeric
LANGUAGE SQL
IMMUTABLE
AS $$
  SELECT round(min_val + (det_int(seed, 100000)::numeric / 100000) * (max_val - min_val), 2);
$$;

-- =========================================================
-- 1) Tables
-- =========================================================

CREATE TABLE chart_of_accounts (
  account_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_code      VARCHAR(10) NOT NULL UNIQUE,
  account_name      VARCHAR(100) NOT NULL,
  account_type      VARCHAR(20) NOT NULL CHECK (account_type IN ('Asset','Liability','Equity','Revenue','Expense')),
  is_active         BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE departments (
  department_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department_code   VARCHAR(10) NOT NULL UNIQUE,
  department_name   VARCHAR(100) NOT NULL,
  cost_center       VARCHAR(20) NOT NULL
);

CREATE TABLE vendors (
  vendor_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_name       VARCHAR(150) NOT NULL,
  vendor_type       VARCHAR(30) NOT NULL CHECK (vendor_type IN ('Software','Facilities','Professional Services','Utilities','Logistics','Marketing','Other')),
  payment_terms     VARCHAR(20) NOT NULL CHECK (payment_terms IN ('Net 15','Net 30','Net 45','Due on receipt')),
  city              VARCHAR(80),
  state             VARCHAR(20)
);

CREATE TABLE customers (
  customer_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name     VARCHAR(150) NOT NULL,
  segment           VARCHAR(30) NOT NULL CHECK (segment IN ('Enterprise','Mid-Market','SMB','Public Sector')),
  city              VARCHAR(80),
  state             VARCHAR(20)
);

CREATE TABLE invoices (
  invoice_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_number    VARCHAR(20) NOT NULL UNIQUE,
  customer_id       INT NOT NULL REFERENCES customers(customer_id),
  invoice_date      DATE NOT NULL,
  due_date          DATE NOT NULL,
  status            VARCHAR(15) NOT NULL CHECK (status IN ('Open','Paid','Partially Paid','Void')),
  currency          CHAR(3) NOT NULL DEFAULT 'USD',
  memo              VARCHAR(200)
);

CREATE TABLE invoice_lines (
  invoice_line_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id        INT NOT NULL REFERENCES invoices(invoice_id) ON DELETE CASCADE,
  line_number       INT NOT NULL,
  description       VARCHAR(200) NOT NULL,
  department_id     INT NOT NULL REFERENCES departments(department_id),
  revenue_account_id INT NOT NULL REFERENCES chart_of_accounts(account_id),
  amount            NUMERIC(12,2) NOT NULL CHECK (amount >= 0)
);

CREATE TABLE bills (
  bill_id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bill_number       VARCHAR(20) NOT NULL UNIQUE,
  vendor_id         INT NOT NULL REFERENCES vendors(vendor_id),
  bill_date         DATE NOT NULL,
  due_date          DATE NOT NULL,
  status            VARCHAR(15) NOT NULL CHECK (status IN ('Open','Paid','Partially Paid','Void')),
  currency          CHAR(3) NOT NULL DEFAULT 'USD',
  memo              VARCHAR(200)
);

CREATE TABLE bill_lines (
  bill_line_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bill_id           INT NOT NULL REFERENCES bills(bill_id) ON DELETE CASCADE,
  line_number       INT NOT NULL,
  description       VARCHAR(200) NOT NULL,
  department_id     INT NOT NULL REFERENCES departments(department_id),
  expense_account_id INT NOT NULL REFERENCES chart_of_accounts(account_id),
  amount            NUMERIC(12,2) NOT NULL CHECK (amount >= 0)
);

CREATE TABLE payments (
  payment_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_number    VARCHAR(20) NOT NULL UNIQUE,
  payment_date      DATE NOT NULL,
  payment_type      VARCHAR(10) NOT NULL CHECK (payment_type IN ('AR','AP')),
  customer_id       INT REFERENCES customers(customer_id),
  vendor_id         INT REFERENCES vendors(vendor_id),
  method            VARCHAR(20) NOT NULL CHECK (method IN ('ACH','Wire','Check','Card')),
  amount            NUMERIC(12,2) NOT NULL CHECK (amount > 0),
  memo              VARCHAR(200),
  CHECK (
    (payment_type = 'AR' AND customer_id IS NOT NULL AND vendor_id IS NULL)
    OR
    (payment_type = 'AP' AND vendor_id IS NOT NULL AND customer_id IS NULL)
  )
);

CREATE TABLE payment_applications (
  payment_application_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id        INT NOT NULL REFERENCES payments(payment_id) ON DELETE CASCADE,
  apply_to_type     VARCHAR(10) NOT NULL CHECK (apply_to_type IN ('Invoice','Bill')),
  invoice_id        INT REFERENCES invoices(invoice_id),
  bill_id           INT REFERENCES bills(bill_id),
  applied_amount    NUMERIC(12,2) NOT NULL CHECK (applied_amount > 0),
  CHECK (
    (apply_to_type = 'Invoice' AND invoice_id IS NOT NULL AND bill_id IS NULL)
    OR
    (apply_to_type = 'Bill' AND bill_id IS NOT NULL AND invoice_id IS NULL)
  )
);

CREATE TABLE journal_entries (
  journal_entry_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  journal_number    VARCHAR(20) NOT NULL UNIQUE,
  entry_date        DATE NOT NULL,
  description       VARCHAR(200) NOT NULL,
  source            VARCHAR(30) NOT NULL CHECK (source IN ('Manual','Accrual','Payroll','Depreciation','Reclass'))
);

CREATE TABLE journal_lines (
  journal_line_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  journal_entry_id  INT NOT NULL REFERENCES journal_entries(journal_entry_id) ON DELETE CASCADE,
  line_number       INT NOT NULL,
  account_id        INT NOT NULL REFERENCES chart_of_accounts(account_id),
  department_id     INT REFERENCES departments(department_id),
  debit             NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (debit >= 0),
  credit            NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (credit >= 0),
  CHECK (NOT (debit > 0 AND credit > 0)),
  CHECK (debit > 0 OR credit > 0)
);

-- =========================================================
-- 2) Reference data: CoA + Departments
-- =========================================================

INSERT INTO chart_of_accounts (account_code, account_name, account_type) VALUES
('1000','Cash','Asset'),
('1100','Accounts Receivable','Asset'),
('1200','Prepaid Expenses','Asset'),
('1500','Equipment','Asset'),
('1600','Accumulated Depreciation','Asset'),
('2000','Accounts Payable','Liability'),
('2100','Accrued Expenses','Liability'),
('2200','Deferred Revenue','Liability'),
('3000','Retained Earnings','Equity'),
('4000','Product Revenue','Revenue'),
('4010','Service Revenue','Revenue'),
('4020','Training Revenue','Revenue'),
('5000','Salaries Expense','Expense'),
('5100','Rent Expense','Expense'),
('5200','Software Subscriptions','Expense'),
('5300','Marketing Expense','Expense'),
('5400','Travel Expense','Expense'),
('5500','Utilities Expense','Expense'),
('5600','Contractor Expense','Expense'),
('5700','Shipping Expense','Expense'),
('5800','Office Supplies Expense','Expense'),
('5900','Depreciation Expense','Expense');

INSERT INTO departments (department_code, department_name, cost_center) VALUES
('FIN','Finance','CC-100'),
('SAL','Sales','CC-200'),
('MKT','Marketing','CC-300'),
('OPS','Operations','CC-400'),
('IT','IT','CC-500'),
('HR','Human Resources','CC-600');

-- =========================================================
-- 3) Parameters (adjust counts here)
-- =========================================================
-- You can edit these values and re-run the script.

WITH params AS (
  SELECT
    150::int  AS n_customers,
    120::int  AS n_vendors,
    1200::int AS n_invoices,
    1200::int AS n_bills,
    120::int  AS n_journal_entries
)
SELECT * FROM params;

-- =========================================================
-- 4) Customers (150) and Vendors (120)
-- =========================================================

WITH params AS (
  SELECT 150::int AS n_customers
),
base AS (
  SELECT gs AS i
  FROM params, generate_series(1, (SELECT n_customers FROM params)) gs
),
name_parts AS (
  SELECT
    i,
    ARRAY['Apex','Blue','Cedar','Greenline','Orion','Summit','Riverside','Northeast','Pioneer','Liberty','Atlas','Evergreen','Redwood','Sterling','Harbor','Clearwater'] AS p1,
    ARRAY['Manufacturing','Retail','Health','Public Library','Education Group','Coffee Roasters','Tech Partners','Insurance','Logistics','Holdings','Consulting','Energy','Pharma','Media','Foods','Construction'] AS p2,
    ARRAY['Inc','LLC','Co','Group','Partners','Systems'] AS p3,
    ARRAY['Enterprise','Mid-Market','SMB','Public Sector'] AS segs,
    ARRAY['New York','Chicago','Austin','Seattle','Denver','Portland','San Jose','Hartford','Boston','Miami','Phoenix','Dallas'] AS cities,
    ARRAY['NY','IL','TX','WA','CO','OR','CA','CT','MA','FL','AZ','TX'] AS states
  FROM base
)
INSERT INTO customers (customer_id, customer_name, segment, city, state)
SELECT
  i AS customer_id,
  (p1[det_int('c_p1_'||i, array_length(p1,1)) + 1] || ' ' ||
   p2[det_int('c_p2_'||i, array_length(p2,1)) + 1] || ' ' ||
   p3[det_int('c_p3_'||i, array_length(p3,1)) + 1]) AS customer_name,
  segs[det_int('c_seg_'||i, array_length(segs,1)) + 1] AS segment,
  cities[det_int('c_city_'||i, array_length(cities,1)) + 1] AS city,
  states[det_int('c_state_'||i, array_length(states,1)) + 1] AS state
FROM name_parts;

WITH params AS (
  SELECT 120::int AS n_vendors
),
base AS (
  SELECT gs AS i
  FROM params, generate_series(1, (SELECT n_vendors FROM params)) gs
),
parts AS (
  SELECT
    i,
    ARRAY['CloudNine','BrightOffice','Metro','Hudson','Peak','Skyline','NorthStar','SecureIT','RapidPrint','UrbanClean','PrimeLegal','SolidWorks','DataBridge','SilverLine','Vertex','Sunrise'] AS p1,
    ARRAY['Software','Supplies','Utilities','Property','Consulting','Logistics','Marketing','Services','Printing','Maintenance','Advisors','Studio','Solutions','Partners'] AS p2,
    ARRAY['Software','Facilities','Professional Services','Utilities','Logistics','Marketing','Other'] AS vtypes,
    ARRAY['Net 15','Net 30','Net 45','Due on receipt'] AS terms,
    ARRAY['New York','Jersey City','Newark','Brooklyn','Boston','Philadelphia','Stamford','Providence'] AS cities,
    ARRAY['NY','NJ','NJ','NY','MA','PA','CT','RI'] AS states
  FROM base
)
INSERT INTO vendors (vendor_id, vendor_name, vendor_type, payment_terms, city, state)
SELECT
  i AS vendor_id,
  (p1[det_int('v_p1_'||i, array_length(p1,1)) + 1] || ' ' ||
   p2[det_int('v_p2_'||i, array_length(p2,1)) + 1]) AS vendor_name,
  vtypes[det_int('v_type_'||i, array_length(vtypes,1)) + 1] AS vendor_type,
  terms[det_int('v_terms_'||i, array_length(terms,1)) + 1] AS payment_terms,
  cities[det_int('v_city_'||i, array_length(cities,1)) + 1] AS city,
  states[det_int('v_state_'||i, array_length(states,1)) + 1] AS state
FROM parts;

-- =========================================================
-- 5) Invoices (1200) + Lines (2 to 3 per invoice)
-- =========================================================

WITH params AS (SELECT 1200::int AS n_invoices),
base AS (
  SELECT gs AS i
  FROM params, generate_series(1, (SELECT n_invoices FROM params)) gs
),
inv AS (
  SELECT
    i,
    'INV-' || to_char(i, 'FM00000') AS invoice_number,
    (det_int('inv_cust_'||i, 150) + 1) AS customer_id,
    (DATE '2025-01-01' + (det_int('inv_date_'||i, 455)) * INTERVAL '1 day')::date AS invoice_date,
    (DATE '2025-01-01' + (det_int('inv_date_'||i, 455)) * INTERVAL '1 day' + INTERVAL '30 days')::date AS due_date,
    CASE
      WHEN det_int('inv_status_'||i, 100) < 8 THEN 'Void'
      WHEN det_int('inv_status_'||i, 100) < 45 THEN 'Open'
      WHEN det_int('inv_status_'||i, 100) < 65 THEN 'Partially Paid'
      ELSE 'Paid'
    END AS status,
    CASE
      WHEN det_int('inv_memo_'||i, 4) = 0 THEN 'Subscription'
      WHEN det_int('inv_memo_'||i, 4) = 1 THEN 'Implementation services'
      WHEN det_int('inv_memo_'||i, 4) = 2 THEN 'Training delivery'
      ELSE 'Support services'
    END AS memo
  FROM base
)
INSERT INTO invoices (invoice_id, invoice_number, customer_id, invoice_date, due_date, status, memo)
SELECT i, invoice_number, customer_id, invoice_date, due_date, status, memo
FROM inv;

-- Invoice lines: 2 to 3 lines per invoice
WITH base AS (
  SELECT invoice_id, invoice_number, memo
  FROM invoices
),
rev_accounts AS (
  SELECT ARRAY[
    (SELECT account_id FROM chart_of_accounts WHERE account_code='4000'),
    (SELECT account_id FROM chart_of_accounts WHERE account_code='4010'),
    (SELECT account_id FROM chart_of_accounts WHERE account_code='4020')
  ] AS acct_ids
),
dept_ids AS (
  SELECT ARRAY[
    (SELECT department_id FROM departments WHERE department_code='SAL'),
    (SELECT department_id FROM departments WHERE department_code='OPS'),
    (SELECT department_id FROM departments WHERE department_code='MKT')
  ] AS dept_ids
)
INSERT INTO invoice_lines (invoice_id, line_number, description, department_id, revenue_account_id, amount)
SELECT
  b.invoice_id,
  ln AS line_number,
  CASE
    WHEN b.memo = 'Subscription' THEN 'Subscription: recurring fees'
    WHEN b.memo = 'Implementation services' THEN 'Implementation: project work'
    WHEN b.memo = 'Training delivery' THEN 'Training: instructor-led session'
    ELSE 'Support: monthly services'
  END || ' (Line ' || ln || ')' AS description,
  (SELECT dept_ids[det_int('il_dept_'||b.invoice_id||'_'||ln, array_length(dept_ids,1)) + 1] FROM dept_ids) AS department_id,
  (SELECT acct_ids[det_int('il_acct_'||b.invoice_id||'_'||ln, array_length(acct_ids,1)) + 1] FROM rev_accounts) AS revenue_account_id,
  CASE
    WHEN b.memo = 'Subscription' THEN det_num('il_amt_'||b.invoice_id||'_'||ln, 1200, 9000)
    WHEN b.memo = 'Implementation services' THEN det_num('il_amt_'||b.invoice_id||'_'||ln, 800, 6000)
    WHEN b.memo = 'Training delivery' THEN det_num('il_amt_'||b.invoice_id||'_'||ln, 500, 4500)
    ELSE det_num('il_amt_'||b.invoice_id||'_'||ln, 250, 2500)
  END AS amount
FROM base b
CROSS JOIN LATERAL generate_series(
  1,
  2 + det_int('il_cnt_'||b.invoice_id, 2) -- 2 or 3
) AS ln;

-- =========================================================
-- 6) Bills (1200) + Lines (2 to 3 per bill)
-- =========================================================

WITH params AS (SELECT 1200::int AS n_bills),
base AS (
  SELECT gs AS i
  FROM params, generate_series(1, (SELECT n_bills FROM params)) gs
),
b AS (
  SELECT
    i,
    'BILL-' || to_char(i, 'FM00000') AS bill_number,
    (det_int('bill_vendor_'||i, 120) + 1) AS vendor_id,
    (DATE '2025-01-01' + (det_int('bill_date_'||i, 455)) * INTERVAL '1 day')::date AS bill_date,
    (DATE '2025-01-01' + (det_int('bill_date_'||i, 455)) * INTERVAL '1 day' + (15 + det_int('bill_due_'||i, 31)) * INTERVAL '1 day')::date AS due_date,
    CASE
      WHEN det_int('bill_status_'||i, 100) < 6 THEN 'Void'
      WHEN det_int('bill_status_'||i, 100) < 40 THEN 'Open'
      WHEN det_int('bill_status_'||i, 100) < 60 THEN 'Partially Paid'
      ELSE 'Paid'
    END AS status,
    CASE
      WHEN det_int('bill_memo_'||i, 5) = 0 THEN 'Rent'
      WHEN det_int('bill_memo_'||i, 5) = 1 THEN 'Software subscription'
      WHEN det_int('bill_memo_'||i, 5) = 2 THEN 'Utilities'
      WHEN det_int('bill_memo_'||i, 5) = 3 THEN 'Consulting'
      ELSE 'Office and operations'
    END AS memo
  FROM base
)
INSERT INTO bills (bill_id, bill_number, vendor_id, bill_date, due_date, status, memo)
SELECT i, bill_number, vendor_id, bill_date, due_date, status, memo
FROM b;

-- Bill lines
WITH base AS (
  SELECT bill_id, bill_number, memo
  FROM bills
),
exp_accounts AS (
  SELECT ARRAY[
    (SELECT account_id FROM chart_of_accounts WHERE account_code='5100'),
    (SELECT account_id FROM chart_of_accounts WHERE account_code='5200'),
    (SELECT account_id FROM chart_of_accounts WHERE account_code='5300'),
    (SELECT account_id FROM chart_of_accounts WHERE account_code='5500'),
    (SELECT account_id FROM chart_of_accounts WHERE account_code='5600'),
    (SELECT account_id FROM chart_of_accounts WHERE account_code='5700'),
    (SELECT account_id FROM chart_of_accounts WHERE account_code='5800')
  ] AS acct_ids
),
dept_ids AS (
  SELECT ARRAY[
    (SELECT department_id FROM departments WHERE department_code='OPS'),
    (SELECT department_id FROM departments WHERE department_code='IT'),
    (SELECT department_id FROM departments WHERE department_code='FIN'),
    (SELECT department_id FROM departments WHERE department_code='MKT'),
    (SELECT department_id FROM departments WHERE department_code='HR')
  ] AS dept_ids
)
INSERT INTO bill_lines (bill_id, line_number, description, department_id, expense_account_id, amount)
SELECT
  b.bill_id,
  ln AS line_number,
  CASE
    WHEN b.memo = 'Rent' THEN 'Office rent and facilities'
    WHEN b.memo = 'Software subscription' THEN 'Software and SaaS tools'
    WHEN b.memo = 'Utilities' THEN 'Utilities and energy'
    WHEN b.memo = 'Consulting' THEN 'Professional services'
    ELSE 'Operations and supplies'
  END || ' (Line ' || ln || ')' AS description,
  (SELECT dept_ids[det_int('bl_dept_'||b.bill_id||'_'||ln, array_length(dept_ids,1)) + 1] FROM dept_ids) AS department_id,
  (SELECT acct_ids[det_int('bl_acct_'||b.bill_id||'_'||ln, array_length(acct_ids,1)) + 1] FROM exp_accounts) AS expense_account_id,
  CASE
    WHEN b.memo = 'Rent' THEN det_num('bl_amt_'||b.bill_id||'_'||ln, 2000, 18000)
    WHEN b.memo = 'Software subscription' THEN det_num('bl_amt_'||b.bill_id||'_'||ln, 200, 7000)
    WHEN b.memo = 'Utilities' THEN det_num('bl_amt_'||b.bill_id||'_'||ln, 150, 2500)
    WHEN b.memo = 'Consulting' THEN det_num('bl_amt_'||b.bill_id||'_'||ln, 500, 15000)
    ELSE det_num('bl_amt_'||b.bill_id||'_'||ln, 50, 1200)
  END AS amount
FROM base b
CROSS JOIN LATERAL generate_series(
  1,
  2 + det_int('bl_cnt_'||b.bill_id, 2) -- 2 or 3
) AS ln;

-- =========================================================
-- 7) Payments + Applications
--    Create payments for Paid and Partially Paid invoices/bills
-- =========================================================

-- AR payments derived from invoice totals
WITH inv_totals AS (
  SELECT
    i.invoice_id,
    i.customer_id,
    i.invoice_date,
    i.status,
    sum(il.amount)::numeric(12,2) AS total_amount
  FROM invoices i
  JOIN invoice_lines il ON il.invoice_id = i.invoice_id
  WHERE i.status IN ('Paid','Partially Paid')
  GROUP BY i.invoice_id, i.customer_id, i.invoice_date, i.status
),
pay AS (
  SELECT
    invoice_id,
    customer_id,
    (invoice_date + (5 + det_int('ar_pay_delay_'||invoice_id, 20)) * INTERVAL '1 day')::date AS payment_date,
    CASE det_int('ar_method_'||invoice_id, 4)
      WHEN 0 THEN 'ACH'
      WHEN 1 THEN 'Wire'
      WHEN 2 THEN 'Check'
      ELSE 'Card'
    END AS method,
    CASE
      WHEN status = 'Paid' THEN total_amount
      ELSE round(total_amount * (0.40 + det_int('ar_partial_'||invoice_id, 41)::numeric / 100), 2) -- 0.40 to 0.80
    END AS paid_amount
  FROM inv_totals
)
INSERT INTO payments (payment_number, payment_date, payment_type, customer_id, method, amount, memo)
SELECT
  'PMT-AR-' || to_char(invoice_id, 'FM00000') AS payment_number,
  payment_date,
  'AR',
  customer_id,
  method,
  paid_amount,
  'Payment for invoice ' || (SELECT invoice_number FROM invoices WHERE invoice_id = pay.invoice_id)
FROM pay;

-- Apply AR payments to invoices
INSERT INTO payment_applications (payment_id, apply_to_type, invoice_id, applied_amount)
SELECT
  p.payment_id,
  'Invoice',
  i.invoice_id,
  p.amount
FROM payments p
JOIN invoices i ON p.memo LIKE '%' || i.invoice_number
WHERE p.payment_type = 'AR';

-- AP payments derived from bill totals
WITH bill_totals AS (
  SELECT
    b.bill_id,
    b.vendor_id,
    b.bill_date,
    b.status,
    sum(bl.amount)::numeric(12,2) AS total_amount
  FROM bills b
  JOIN bill_lines bl ON bl.bill_id = b.bill_id
  WHERE b.status IN ('Paid','Partially Paid')
  GROUP BY b.bill_id, b.vendor_id, b.bill_date, b.status
),
pay AS (
  SELECT
    bill_id,
    vendor_id,
    (bill_date + (7 + det_int('ap_pay_delay_'||bill_id, 25)) * INTERVAL '1 day')::date AS payment_date,
    CASE det_int('ap_method_'||bill_id, 4)
      WHEN 0 THEN 'ACH'
      WHEN 1 THEN 'Wire'
      WHEN 2 THEN 'Check'
      ELSE 'Card'
    END AS method,
    CASE
      WHEN status = 'Paid' THEN total_amount
      ELSE round(total_amount * (0.35 + det_int('ap_partial_'||bill_id, 46)::numeric / 100), 2) -- 0.35 to 0.80
    END AS paid_amount
  FROM bill_totals
)
INSERT INTO payments (payment_number, payment_date, payment_type, vendor_id, method, amount, memo)
SELECT
  'PMT-AP-' || to_char(bill_id, 'FM00000') AS payment_number,
  payment_date,
  'AP',
  vendor_id,
  method,
  paid_amount,
  'Payment for bill ' || (SELECT bill_number FROM bills WHERE bill_id = pay.bill_id)
FROM pay;

-- Apply AP payments to bills
INSERT INTO payment_applications (payment_id, apply_to_type, bill_id, applied_amount)
SELECT
  p.payment_id,
  'Bill',
  b.bill_id,
  p.amount
FROM payments p
JOIN bills b ON p.memo LIKE '%' || b.bill_number
WHERE p.payment_type = 'AP';

-- =========================================================
-- 8) Journal entries (120) + lines (2 each)
-- =========================================================

WITH je AS (
  SELECT
    journal_entry_id,
    journal_number,
    source,
    det_num('je_amt_' || journal_entry_id, 250, 6000) AS amount
  FROM journal_entries
),
acct AS (
  SELECT
    (SELECT account_id FROM chart_of_accounts WHERE account_code='5600') AS contractor_exp,
    (SELECT account_id FROM chart_of_accounts WHERE account_code='2100') AS accrued_exp,
    (SELECT account_id FROM chart_of_accounts WHERE account_code='5900') AS depr_exp,
    (SELECT account_id FROM chart_of_accounts WHERE account_code='1600') AS accum_depr,
    (SELECT account_id FROM chart_of_accounts WHERE account_code='5300') AS mkt_exp,
    (SELECT account_id FROM chart_of_accounts WHERE account_code='5000') AS sal_exp,
    (SELECT account_id FROM chart_of_accounts WHERE account_code='1000') AS cash
),
depts AS (
  SELECT
    (SELECT department_id FROM departments WHERE department_code='FIN') AS fin,
    (SELECT department_id FROM departments WHERE department_code='SAL') AS sal,
    (SELECT department_id FROM departments WHERE department_code='MKT') AS mkt,
    (SELECT department_id FROM departments WHERE department_code='OPS') AS ops
)

INSERT INTO journal_lines (journal_entry_id, line_number, account_id, department_id, debit, credit)

-- Line 1: Debit
SELECT
  je.journal_entry_id,
  1 AS line_number,
  CASE
    WHEN je.source = 'Accrual' THEN acct.contractor_exp
    WHEN je.source = 'Depreciation' THEN acct.depr_exp
    WHEN je.source = 'Reclass' THEN acct.sal_exp
    WHEN je.source = 'Payroll' THEN acct.sal_exp
    ELSE acct.contractor_exp
  END AS account_id,
  CASE
    WHEN je.source = 'Reclass' THEN depts.sal
    WHEN je.source = 'Depreciation' THEN depts.ops
    WHEN je.source = 'Accrual' THEN depts.fin
    ELSE depts.ops
  END AS department_id,
  je.amount AS debit,
  0::numeric AS credit
FROM je, acct, depts

UNION ALL

-- Line 2: Credit (same amount, opposite side)
SELECT
  je.journal_entry_id,
  2 AS line_number,
  CASE
    WHEN je.source = 'Accrual' THEN acct.accrued_exp
    WHEN je.source = 'Depreciation' THEN acct.accum_depr
    WHEN je.source = 'Reclass' THEN acct.mkt_exp
    WHEN je.source = 'Payroll' THEN acct.cash
    ELSE acct.accrued_exp
  END AS account_id,
  CASE
    WHEN je.source = 'Reclass' THEN depts.mkt
    WHEN je.source = 'Depreciation' THEN depts.ops
    WHEN je.source = 'Accrual' THEN depts.fin
    ELSE NULL
  END AS department_id,
  0::numeric AS debit,
  je.amount AS credit
FROM je, acct, depts;

-- =========================================================
-- 9) View for exercises: transaction-like dataset
-- Sign convention:
--   Revenue positive
--   Expense negative
-- =========================================================

CREATE VIEW v_finance_activity AS
SELECT
  'AR' AS source,
  i.invoice_date AS txn_date,
  to_char(i.invoice_date, 'YYYY-MM') AS txn_month,
  i.invoice_number AS document_number,
  c.customer_name AS counterparty,
  d.department_name,
  coa.account_code,
  coa.account_name,
  coa.account_type,
  il.amount AS amount
FROM invoices i
JOIN customers c ON c.customer_id = i.customer_id
JOIN invoice_lines il ON il.invoice_id = i.invoice_id
JOIN departments d ON d.department_id = il.department_id
JOIN chart_of_accounts coa ON coa.account_id = il.revenue_account_id

UNION ALL

SELECT
  'AP' AS source,
  b.bill_date AS txn_date,
  to_char(b.bill_date, 'YYYY-MM') AS txn_month,
  b.bill_number AS document_number,
  v.vendor_name AS counterparty,
  d.department_name,
  coa.account_code,
  coa.account_name,
  coa.account_type,
  (bl.amount * -1) AS amount
FROM bills b
JOIN vendors v ON v.vendor_id = b.vendor_id
JOIN bill_lines bl ON bl.bill_id = b.bill_id
JOIN departments d ON d.department_id = bl.department_id
JOIN chart_of_accounts coa ON coa.account_id = bl.expense_account_id

UNION ALL

SELECT
  'JE' AS source,
  je.entry_date AS txn_date,
  to_char(je.entry_date, 'YYYY-MM') AS txn_month,
  je.journal_number AS document_number,
  je.description AS counterparty,
  COALESCE(d.department_name, 'Unassigned') AS department_name,
  coa.account_code,
  coa.account_name,
  coa.account_type,
  (jl.debit - jl.credit) AS amount
FROM journal_entries je
JOIN journal_lines jl ON jl.journal_entry_id = je.journal_entry_id
JOIN chart_of_accounts coa ON coa.account_id = jl.account_id
LEFT JOIN departments d ON d.department_id = jl.department_id;

-- =========================================================
-- 10) Quick sanity checks (optional, but useful)
-- =========================================================
-- SELECT 'customers' AS table, count(*) FROM customers
-- UNION ALL SELECT 'vendors', count(*) FROM vendors
-- UNION ALL SELECT 'invoices', count(*) FROM invoices
-- UNION ALL SELECT 'invoice_lines', count(*) FROM invoice_lines
-- UNION ALL SELECT 'bills', count(*) FROM bills
-- UNION ALL SELECT 'bill_lines', count(*) FROM bill_lines
-- UNION ALL SELECT 'payments', count(*) FROM payments
-- UNION ALL SELECT 'payment_applications', count(*) FROM payment_applications
-- UNION ALL SELECT 'journal_entries', count(*) FROM journal_entries
-- UNION ALL SELECT 'journal_lines', count(*) FROM journal_lines
-- UNION ALL SELECT 'v_finance_activity (rows)', count(*) FROM v_finance_activity;

-- Suggested first student query:
-- SELECT * FROM v_finance_activity LIMIT 25;